PACKAGE = FitRunner

CXXFLAGS=-I$(SRC) -I$(HOME)/bin/atlasstyle-trunk #-I$(TBB_INC) 

BINLINKFLAGS = -L$(LIBDIR) -lTcore -lTfunctions -lTFitterInputs -lTFitterResults -ltbb #-I$(TBB_INC) #-L$(TBB_LIB)

include $(SRC)/GNUmakefiles/GNUmakefile
